import { StyleSheet } from 'react-native';

export const productCardStyles = StyleSheet.create ({
  card: {
    borderRadius: 32,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 12,
    padding: 20,
    width: 280,
  },
  image: {
    width: 260,
    height: 140,
    borderRadius: 24,
    marginBottom: 18,
    alignSelf: 'center' as 'center',
  },
  name: {
    fontSize: 18,
    fontWeight: '600' as const,
    marginBottom: 2,
    color: '#222',
  },
  price: {
    fontSize: 16,
    color: '#222',
    marginBottom: 10,
  },
  controls: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'flex-end' as const,
    marginTop: 2,
  },
  minusButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#F3F4F6',
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    marginRight: 4,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  minusText: {
    fontSize: 18,
    color: '#888',
    fontWeight: 'bold' as const,
  },
  quantity: {
    fontSize: 16,
    color: '#222',
    marginHorizontal: 6,
  },
  plusButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#C0E863',
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    marginLeft: 4,
  },
  plusText: {
    fontSize: 18,
    color: '#222',
    fontWeight: 'bold' as const,
  },
  pillControls: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'flex-end' as const,
    backgroundColor: '#F3F4F6',
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 4,
    marginTop: 12,
    width: 110,
    alignSelf: 'flex-end' as 'flex-end',
  },
  
  pillControlsV2: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    backgroundColor: '#F3F4F6',
    borderRadius: 24,
    paddingHorizontal: 18,
    paddingVertical: 8,
    marginTop: 24,
    width: 140,
    alignSelf: 'center' as 'center',
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 8,
  },
  minusButtonV2: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#E5E7EB',
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    marginRight: 8,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  plusButtonV2: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#C0E863',
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    marginLeft: 8,
    borderWidth: 1,
    borderColor: '#C0E863',
  },
  imageTopRounded: {
    width: 220,
    height: 110,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    marginBottom: 16,
    alignSelf: 'center' as 'center',
  },
});

productCardStyles.pillControls = {
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'flex-end',
  backgroundColor: '#F3F4F6',
  borderRadius: 20,
  paddingHorizontal: 10,
  paddingVertical: 4,
  marginTop: 12,
  width: 110,
  alignSelf: 'flex-end',
};

export default productCardStyles;